###################################################
# aws_instance
###################################################

###################################################
# tags
###################################################
tags:
  "common_tags":
    Project: "jeff-project"
    Team: "jeff-team"
