name: apply-ec2

on:
  push:
    branches:
      - main

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # - name: Install Terraform
    #   uses: hashicorp/setup-terraform@v1
    #   with:
    #     terraform_version: "1.1.0"

    - name: Terraform Format
      run: terraform fmt -check -diff ./ec2

    # - name: Terraform Validate
    #   run: terraform validate ./ec2

    - name: Terraform Plan
      run: terraform plan ./ec2

    - name: Terraform Apply
      run: terraform apply -auto-approve ./ec2
