# Appear as the action's name on the GitHub Actions page
name: (WF)schedule

# Set conditions for Github Action to run
on:
  schedule:
    - cron: '46 6 * * *' # 01:00 KST (UTC+9) is 16:00 UTC

# Options for concurrency management
concurrency: ${{ github.workflow }}

# Define the task to be executed in Github Action
jobs:
  apply-destroy-stop-start:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_ACTION: "stop"
      INSTANCE_TYPE: "t3.medium"
      INSTANCE_ID: "i-0fab2100b97ca6b64"

    defaults:
      run:
        shell: bash
        working-directory: ./ec2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.8

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Apply or Destroy
        run: |
          if [ "$TF_ACTION" == "apply" ]; then
            terraform apply -auto-approve -var="instance_type=$INSTANCE_TYPE"
          elif [ "$TF_ACTION" == "destroy" ]; then
            terraform destroy -auto-approve
          fi

      - name: Terraform Stop or Start EC2 Instance
        run: |
          if [ "$TF_ACTION" == "stop" ]; then
            aws ec2 stop-instances --instance-ids "$INSTANCE_ID"
          elif [ "$TF_ACTION" == "start" ]; then
            aws ec2 start-instances --instance-ids "$INSTANCE_ID"
          fi
