name: Stop EC2 Instance
on:
  workflow_call:
    inputs:
      instance_id:
        description: 'The ID of the EC2 instance to stop'
        required: false
        type: string
      working-directory:
        required: true
        type: string
    secrets:
      aws-region:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  stop-ec2-instance:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.8
      # - name: Remove Lock File
      #   run: rm -f .terraform.lock.hcl

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Stop EC2 Instance
        run: |
          INSTANCE_ID=$(terraform output instance_id | sed 's/"//g')
          aws ec2 stop-instances --instance-ids $INSTANCE_ID
